version: '3'

tasks:
  build:
    desc: Build the whole application with frontend and backend.
    cmds:
      - task: build:frontend
      - task: build:backend

  build:frontend:
    desc: Build the embeded Vite based frontend.
    dir: view
    cmds:
      - yarn
      - yarn run build

  build:backend:
    desc: Build the Golang server backend.
    cmds:
      - cmd: go mod download
      - cmd: GOOS=linux GOARCH=amd64 go build -v -trimpath -ldflags="-s -w" -o bin/furnace-monitoring-system-server .
        platforms: [ linux ]
      - cmd: GOOS=windows GOARCH=amd64 go build -v trimpath -ldflags="-s -w" -o bin/furnace-monitoring-system-server.exe .
        platforms: [ windows ]
